### ISSUE TITLE
Missing Port py27-flac during install

### ISSUE THREAD

**Issue by jgriffter** [eehmke/flactag#1]
Great little program for the Pono player.  Trying to install and all goes well except for step "port install py27-flac" where "Port py27-flac not found".  Search on MacPorts indicates not available.

Could be pilot error.  All other install steps working correctly.  Running  OSX Mojave.  Any assistance would be greatly appreciated.

Griffster

**Comment by eehmke** [comment]
Hallo,
Did you follow the steps in the README? The program was developed for Linux and then adapted for Mac. You may need some help from some Mac expert.

Regards
Eggert 

Am 28. Juli 2019 23:34:08 MESZ schrieb jgriffter <notifications@github.com>:
>Great little program for the Pono player.  Trying to install and all
>goes well except for step "port install py27-flac" where "Port
>py27-flac not found".  Search on MacPorts indicates not available.
>
>Could be pilot error.  All other install steps working correctly. 
>Running  OSX Mojave.  Any assistance would be greatly appreciated.
>
>Griffster
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/eehmke/flactag/issues/1

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jgriffter** [comment]
Eggert,
Thank you.  I did follow the README closely.  Appears the issue might be within the port library of MacPorts.  Three of the four steps installed perfectly.  The step that installs py27-flac indicated a missing port.  I will see if i can get it working in Linux.

Regards,

John
